In [1]:
# primer escrapeo

In [2]:
from funciones import *

In [3]:
%%time
df_final=pd.DataFrame()
i = 1
for i in range(1,101):
    try:
        print(f'iteración {i}')
        
        
        url = f'https://www.futbin.com/22/players?page={i}'
        var = data1(url)
        df_final = pd.concat([df_final,var], axis=0)
        print('finalizado')
        i = i + 1
    except:
        pass
    
    if i == 101:
        break
df_final=df_final.reset_index(drop = True)

iteración 1
finalizado
iteración 2
finalizado
iteración 3
finalizado
iteración 4
finalizado
iteración 5
finalizado
iteración 6
finalizado
iteración 7
finalizado
iteración 8
finalizado
iteración 9
finalizado
iteración 10
finalizado
iteración 11
finalizado
iteración 12
finalizado
iteración 13
finalizado
iteración 14
finalizado
iteración 15
finalizado
iteración 16
finalizado
iteración 17
finalizado
iteración 18
finalizado
iteración 19
finalizado
iteración 20
finalizado
iteración 21
finalizado
iteración 22
finalizado
iteración 23
finalizado
iteración 24
finalizado
iteración 25
finalizado
iteración 26
finalizado
iteración 27
finalizado
iteración 28
finalizado
iteración 29
finalizado
iteración 30
finalizado
iteración 31
finalizado
iteración 32
finalizado
iteración 33
finalizado
iteración 34
finalizado
iteración 35
finalizado
iteración 36
finalizado
iteración 37
finalizado
iteración 38
finalizado
iteración 39
finalizado
iteración 40
finalizado
iteración 41
finalizado
iteración 42
finalizado
iteración 43
finalizado
iteración 44
finalizado
iteración 45
finalizado
iteración 46
finalizado
iteración 47
finalizado
iteración 48
finalizado
iteración 49
finalizado
iteración 50
finalizado
iteración 51
finalizado
iteración 52
finalizado
iteración 53
finalizado
iteración 54
finalizado
iteración 55
finalizado
iteración 56
finalizado
iteración 57
finalizado
iteración 58
finalizado
iteración 59
finalizado
iteración 60
finalizado
iteración 61
finalizado
iteración 62
finalizado
iteración 63
finalizado
iteración 64
finalizado
iteración 65
finalizado
iteración 66
finalizado
iteración 67
finalizado
iteración 68
finalizado
iteración 69
finalizado
iteración 70
finalizado
iteración 71
finalizado
iteración 72
finalizado
iteración 73
finalizado
iteración 74
finalizado
iteración 75
finalizado
iteración 76
finalizado
iteración 77
finalizado
iteración 78
finalizado
iteración 79
finalizado
iteración 80
finalizado
iteración 81
finalizado
iteración 82
finalizado
iteración 83
finalizado
iteración 84
finalizado
iteración 85
finalizado
iteración 86
finalizado
iteración 87
finalizado
iteración 88
finalizado
iteración 89
finalizado
iteración 90
finalizado
iteración 91
finalizado
iteración 92
finalizado
iteración 93
finalizado
iteración 94
finalizado
iteración 95
finalizado
iteración 96
finalizado
iteración 97
finalizado
iteración 98
finalizado
iteración 99
finalizado
iteración 100
finalizado
CPU times: total: 18 s
Wall time: 20min 15s

In [4]:
df_final.to_json('scrap_players.json', orient = 'records' )
scrap_players = df_final.to_csv('scrap_players.csv', sep =' ')

-----------------------------------------------------------------------------------------------------------------------------

In [5]:
# segundo escrapeo

In [6]:
%%time
df_final2=pd.DataFrame()
i = 1
for n in range(0,3001,60):
    try:
        print(f'iteración {1}')
        url = f'https://sofifa.com/players?offset={n}'
        var = data2(url)
        df_final2 = pd.concat([df_final2,var], axis=0)
        print('finalizado')
        i = n/60
    except:
        pass
    
    if n == 3001:
        break
df_final2=df_final2.reset_index(drop = True)

iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
iteración 1
finalizado
CPU times: total: 23.1 s
Wall time: 7min 3s

In [7]:
df_final2.to_json('scrap_players2.json', orient = 'records' )
scrap_players2 = df_final2.to_csv('scrap_players2.csv', sep =' ')

In [8]:
scrap_players2 = df_final2.to_csv('scrap_players2.csv', sep =' ')

-----

In [9]:
#descarga csv

In [10]:
path = '../Fifa22_Player_Segmentation/Final_Table.csv'
playersgit = pd.read_csv(path)

In [11]:
playersgit[['short_name', 'club_logo_url', 'nation_flag_url']].head()

,short_name,club_logo_url,nation_flag_url
0,L. Messi,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/ar.png
1,R. Lewandowski,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/pl.png
2,Cristiano Ronaldo,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/pt.png
3,Neymar Jr,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/br.png
4,K. De Bruyne,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/be.png

---

In [12]:
#limpieza

In [13]:
import pandas as pd
df_final2 = pd.read_csv('scrap_players2.csv', sep = ' ')
df_final = pd.read_csv('scrap_players.csv', sep = ' ')

In [14]:
dic={}
keys = list(df_final2['names'])
values = list(df_final2['equipos'])
for i in range(len(keys)):
    dic[keys[i]]=values[i]

In [15]:
team = {}
for i in dic.keys():
    for j in df_final.name_player:
        if j in i:
            team[j]=dic[i]
        else:
            pass

In [16]:
team_player=[]
for ind, val in enumerate(df_final.name_player):
    if val in list(team.keys()):
        team_player.append(team[val])
    else:
        team_player.append('None')

In [17]:
df_final['team_player']=team_player

In [18]:
df_final=df_final[['name_player', 'team_player', 'media', 'posicion', 'tipo', 'precio',
       'skill', 'wf', 'ritmo', 'shot', 'pas', 'drib', 'def', 'phy',
       'popularity', 'base stats', 'igs', 'plataforma', 'time']]

KeyError: "['precio_player'] not in index"

In [19]:
df_final

,name_player,team_player,media,posicion,tipo,precio,skill,wf,ritmo,shot,pas,drib,def,phy,popularity,base stats,igs,plataforma,time
0,Pelé,None,99,CAM,Icon Moments,2.68M,5,4,96,97,96,97,62,79,2230,527,2563,play-station,Tue Sep 6 07:39:39 2022
1,Lionel Messi,None,99,CF,ShapeShifters,1.75M,5,4,95,98,99,99,42,78,3929,511,2485,play-station,Tue Sep 6 07:39:39 2022
2,Cristiano Ronaldo,Manchester United,99,LW,ShapeShifters,1.8M,5,4,99,99,90,97,50,92,4367,527,2549,play-station,Tue Sep 6 07:39:39 2022
3,Raphaël Varane,None,99,CB,Premium Futties SBC,818.75K,2,3,96,61,80,83,99,98,2166,517,2378,play-station,Tue Sep 6 07:39:39 2022
4,Ousmane Dembélé,None,99,RW,Premium Futties,1.16M,5,5,99,96,94,99,49,79,1843,516,2488,play-station,Tue Sep 6 07:39:39 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Abdoulaye Doucouré,None,79,CM,Normal,1K,3,3,70,76,72,76,77,81,229,452,2091,play-station,Tue Sep 6 07:59:46 2022
2996,Berat Djimsiti,None,79,CB,Normal,1.1K,2,3,68,39,59,50,82,79,20,377,1733,play-station,Tue Sep 6 07:59:46 2022
2997,Christian Günter,None,79,LB,Normal,1.2K,3,2,83,55,70,70,74,81,124,433,1993,play-station,Tue Sep 6 07:59:46 2022
2998,Raúl De Tomás Gómez,None,79,ST,Normal,1K,4,4,75,82,68,81,35,68,41,409,1995,play-station,Tue Sep 6 07:59:46 2022
2999,Jonas Hofmann,None,79,CM,Normal,1.1K,3,4,75,72,80,79,57,66,17,429,2060,play-station,Tue Sep 6 07:59:46 2022

In [20]:
df_final.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name_player  3000 non-null   object
 1   team_player  3000 non-null   object
 2   media        3000 non-null   int64
 3   posicion     3000 non-null   object
 4   tipo         3000 non-null   object
 5   precio       3000 non-null   object
 6   skill        3000 non-null   int64
 7   wf           3000 non-null   int64
 8   ritmo        3000 non-null   int64
 9   shot         3000 non-null   int64
 10  pas          3000 non-null   int64
 11  drib         3000 non-null   int64
 12  def          3000 non-null   int64
 13  phy          3000 non-null   int64
 14  popularity   3000 non-null   int64
 15  base stats   3000 non-null   int64
 16  igs          3000 non-null   int64
 17  plataforma   3000 non-null   object
 18  time         3000 non-null   object
dtypes: int64(12), object(7)
memory usage: 1.6 MB

In [23]:
df_final['media'] = df_final['media'].astype('int16')
df_final['skill'] = df_final['skill'].astype('int16')
df_final['wf'] = df_final['wf'].astype('int16')
df_final['ritmo'] = df_final['ritmo'].astype('int16')
df_final['shot'] = df_final['shot'].astype('int16')
df_final['pas'] = df_final['pas'].astype('int16')
df_final['drib'] = df_final['drib'].astype('int16')
df_final['def'] = df_final['def'].astype('int16')
df_final['phy'] = df_final['phy'].astype('int16')
df_final['popularity'] = df_final['popularity'].astype('int32')
df_final['base stats'] = df_final['base stats'].astype('int32')
df_final['igs'] = df_final['igs'].astype('int32')

In [24]:
df_final.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name_player  3000 non-null   object
 1   team_player  3000 non-null   object
 2   media        3000 non-null   int16
 3   posicion     3000 non-null   object
 4   tipo         3000 non-null   object
 5   precio       3000 non-null   object
 6   skill        3000 non-null   int16
 7   wf           3000 non-null   int16
 8   ritmo        3000 non-null   int16
 9   shot         3000 non-null   int16
 10  pas          3000 non-null   int16
 11  drib         3000 non-null   int16
 12  def          3000 non-null   int16
 13  phy          3000 non-null   int16
 14  popularity   3000 non-null   int32
 15  base stats   3000 non-null   int32
 16  igs          3000 non-null   int32
 17  plataforma   3000 non-null   object
 18  time         3000 non-null   object
dtypes: int16(9), int32(3), object(7)
memory usage: 1.4 MB

In [25]:
df_final

,name_player,team_player,media,posicion,tipo,precio,skill,wf,ritmo,shot,pas,drib,def,phy,popularity,base stats,igs,plataforma,time
0,Pelé,None,99,CAM,Icon Moments,2.68M,5,4,96,97,96,97,62,79,2230,527,2563,play-station,Tue Sep 6 07:39:39 2022
1,Lionel Messi,None,99,CF,ShapeShifters,1.75M,5,4,95,98,99,99,42,78,3929,511,2485,play-station,Tue Sep 6 07:39:39 2022
2,Cristiano Ronaldo,Manchester United,99,LW,ShapeShifters,1.8M,5,4,99,99,90,97,50,92,4367,527,2549,play-station,Tue Sep 6 07:39:39 2022
3,Raphaël Varane,None,99,CB,Premium Futties SBC,818.75K,2,3,96,61,80,83,99,98,2166,517,2378,play-station,Tue Sep 6 07:39:39 2022
4,Ousmane Dembélé,None,99,RW,Premium Futties,1.16M,5,5,99,96,94,99,49,79,1843,516,2488,play-station,Tue Sep 6 07:39:39 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Abdoulaye Doucouré,None,79,CM,Normal,1K,3,3,70,76,72,76,77,81,229,452,2091,play-station,Tue Sep 6 07:59:46 2022
2996,Berat Djimsiti,None,79,CB,Normal,1.1K,2,3,68,39,59,50,82,79,20,377,1733,play-station,Tue Sep 6 07:59:46 2022
2997,Christian Günter,None,79,LB,Normal,1.2K,3,2,83,55,70,70,74,81,124,433,1993,play-station,Tue Sep 6 07:59:46 2022
2998,Raúl De Tomás Gómez,None,79,ST,Normal,1K,4,4,75,82,68,81,35,68,41,409,1995,play-station,Tue Sep 6 07:59:46 2022
2999,Jonas Hofmann,None,79,CM,Normal,1.1K,3,4,75,72,80,79,57,66,17,429,2060,play-station,Tue Sep 6 07:59:46 2022

In [30]:
from pymongo import MongoClient
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
cursor = MongoClient("mongodb://localhost:27017")

In [31]:
cursor

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [32]:
db=cursor.Fifa22  #nueva base de datos
colec=db.players22   # nueva coleccion

In [33]:
db.players22.insert_many(df_final.apply(lambda x: x.to_dict(), axis=1).to_list())